[db]
path = "./corrosion.db"
schema_paths = ["../../corrosion/schemas"]

[gossip]
addr = "127.0.0.1:8788"
bootstrap = ["127.0.0.1:8787"]
plaintext = true

[api]
addr = "127.0.0.1:8082"

[admin]
path = "./admin.sock"
